# This is a basic workflow to help you get started with Actions

name: Tests pass

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: src/stock_scanner
      - name: Run Tests
        run: python -m unittest 
        working-directory: .
        
      - name: Automatic requirements.txt for Python Projects
        uses: ryan-rozario/pipreqs-action@v2.0.0
        with:
          # Gives the path of the project
          PROJECT_PATH: ./src/stock_scanner
          REQUIREMENT_PATH: ./src/stock_scanner/requirements.txt
          # Folder where requirements.txt has to be saved in
          # Name of the project to include in the commit
          PROJECT_NAME: Stock Scanner
